name: pulse-server
adopt-info: pulseaudio
summary: PulseAudio sound server
description: |
  This pulseaudio sound server snap is created for use on an Ubuntu Core
  device to provide audio record and playback capabilities via the
  respective snap interfaces.

grade: stable
confinement: strict
base: core22
compression: lzo

apps:
  pulseaudio:
    command: bin/pulseaudio
    daemon: simple
    plugs:
      - alsa
      - bluez
      - hardware-observe
      - network
      - network-bind
    slots:
      - audio-playback
      - audio-record
      - dbus-svc
  pactl:
    command-chain: [bin/client-wrapper]
    command: usr/bin/pactl
    plugs:
      - network
      - playback
      - record
  paplay:
    command-chain: [bin/client-wrapper]
    command: usr/bin/paplay
    plugs:
      - home
      - network
      - playback
  parec:
    command-chain: [bin/client-wrapper]
    command: usr/bin/parec
    plugs:
      - home
      - network
      - playback
      - record
  config:
    command: bin/config

plugs:
  playback:
    interface: audio-playback
  record:
    interface: audio-record

slots:
  dbus-svc:
    interface: dbus
    bus: system
    name: org.pulseaudio.Server

environment:
  PULSE_RUNTIME_PATH: /var/run/pulse
  PULSE_STATE_PATH: $SNAP_COMMON/state
  ALSA_CONFIG_UCM: $SNAP/usr/share/alsa/ucm2
  ALSA_CONFIG_TPLG: $SNAP/usr/share/alsa/topology
  ALSA_CONFIG_PATH: $SNAP/usr/share/alsa/alsa.conf
  ALSA_MIXER_SIMPLE: $SNAP/usr/share/alsa/smixer.conf
  ALSA_PLUGIN_DIR: $SNAP/usr/lib/alsa-lib

layout:
  /etc/pulse:
    bind: $SNAP/etc/pulse
  /etc/alsa:
    bind: $SNAP/etc/alsa
  /var/lib/pulse:
    bind: $SNAP_DATA
  /usr/lib/pulseaudio:
    symlink: $SNAP/usr/lib/pulseaudio
  /usr/lib/alsa-lib:
    bind: $SNAP/usr/lib/alsa-lib
  /usr/share/pulseaudio:
    symlink: $SNAP/usr/share/pulseaudio
  /usr/share/alsa:
    symlink: $SNAP/usr/share/alsa
  /usr/share/applications:
    bind: $SNAP/usr/share/applications

parts:
  pulseaudio-common:
    source: bin
    plugin: dump
    organize:
      client-wrapper: bin/client-wrapper
      config: bin/config
      pulseaudio: bin/pulseaudio
  alsa-lib:
    plugin: autotools
    source: https://github.com/alsa-project/alsa-lib.git
    source-tag: v1.2.11
    prime:
      - -usr/include
      - -usr/share/aclocal
      - -usr/lib/libatopology*
      - -usr/lib/lib*.la
      - -usr/lib/pkgconfig
  pulseaudio:
    plugin: meson
    source: https://github.com/pulseaudio/pulseaudio.git
    source-tag: v17.0
    source-depth: 1
    after: [ alsa-lib ]
    build-packages:
      - check
      - doxygen
      - intltool
      - libapparmor-dev
      - libdbus-1-dev
      - libjson-c-dev
      - libglib2.0-dev
      - libspeexdsp-dev
      - libbluetooth-dev
      - libltdl-dev
      - libsndfile1-dev
      - libtdb-dev
      - libudev-dev
      - libasyncns-dev
      - libsbc-dev
      - libsnapd-glib-dev
      - libsoxr-dev
      - meson
    stage-packages:
      - libasyncns0
      - libflac8
      - libgomp1
      - libltdl7
      - libogg0
      - libsbc1
      - libsndfile1
      - libsoxr0
      - libspeexdsp1
      - libtdb1
      - libudev1
      - libvorbis0a
      - libvorbisenc2
    meson-parameters:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - -Dgstreamer=disabled
      - -Dbluez5-gstreamer=disabled
      - -Dorc=disabled
      - -Dgsettings=disabled
      - -Dadrian-aec=false
      - -Dgtk=disabled
      - -Dhal-compat=false
      - -Dwebrtc-aec=disabled
      - -Doss-output=disabled
      - -Djack=disabled
      - -Dx11=disabled
      - -Dsystem_user=root
      - -Dsystem_group=root
      - -Daccess_group=root
    override-build: |
      craftctl default
      VER=$(cd $SNAPCRAFT_PART_SRC; git tag|sed 's/^v//')
      craftctl set version=$VER
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
    override-prime: |
      craftctl default
      echo "load-module module-switch-on-connect" >> etc/pulse/system.pa
      sed --in-place "s/user=\"pulse\"/user=\"root\"/" usr/share/dbus-1/system.d/pulseaudio-system.conf
      find usr/share/doc/ -type f,l ! -name copyright | xargs rm -rf
    prime:
      - -usr/include
      - -usr/share/zsh
      - -usr/share/bash-completion
      - -usr/share/man
      - -usr/share/GConf
      - -usr/share/lintian
      - -usr/share/vala
      - -usr/libexec
      - -usr/lib/cmake
      - -usr/lib/libpulse-mainloop-glib*
      - -usr/lib/libpulse-simple*
      - -usr/lib/pkgconfig
      - -usr/lib/systemd
      - -etc/dconf
  alsa-plugins:
    plugin: autotools
    source: https://github.com/alsa-project/alsa-plugins.git
    source-tag: v1.2.7.1
    after: [ pulseaudio, alsa-lib ]
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-alsalconfdir=/etc/alsa/conf.d
      - --sysconfdir=/etc/alsa/conf.d
    prime:
      - -usr/lib/alsa-lib/*.la
    override-prime: |
      craftctl default
      # make links relative
      cd etc/alsa/conf.d
      for link in $(find . -type l); do
        newlink=$(readlink $link|sed 's;^/;../../../;')
        ln -sf $newlink $link
      done
      cd -
  alsa-ucm:
    plugin: dump
    source: https://github.com/alsa-project/alsa-ucm-conf.git
    source-tag: v1.2.11
    after: [ alsa-plugins ]
    organize:
      ucm: usr/share/alsa/ucm
      ucm2: usr/share/alsa/ucm2
    prime:
      - -README.md
      - -VERSION
      - -*/**/*.md
      - -*/**/*.gitignore
